/*------USUARIOS--------
INSERT INTO TAB_USUARIOS (NOME, EMAIL, DATA_NASCIMENTO) 
VALUES('MARIA SILVA', 'MARIA@EMAIL.COM', '07/09/2008');

UPDATE TAB_USUARIOS SET EMAIL = 'JOAO900@EMAIL.COM' WHERE ID = 4;

DELETE FROM TAB_USUARIOS WHERE ID = 5;

ALTER TABLE TAB_USUARIOS
ADD COLUMN IDADE SMALLINT NOT NULL DEFAULT 0;

INSERT INTO TAB_USUARIOS (NOME, EMAIL, DATA_NASCIMENTO, IDADE)
VALUES ('JOAO CLEBER', 'JOAOC@EMAIL.COM', '10/10/2010', 16);

ALTER TABLE TAB_USUARIOS
DROP COLUMN IDADE;
SELECT  * FROM TAB_USUARIOS;

------PEDIDOS--------
CREATE TABLE TAB_PEDIDOS(
	COD_PEDIDO SERIAL PRIMARY KEY,
	ID_USUARIO INT REFERENCES TAB_USUARIOS(ID),
	DATA_PEDIDO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO TAB_PEDIDOS(ID_USUARIO)
VALUES (6);
SELECT * FROM TAB_PEDIDOS;*/